### ISSUE TITLE
Error importing AnimationMain from Core.helper.animation

### ISSUE THREAD

**Issue by Bellisario** [BiZken/PhishMailer#20]
Here is the console error:
![image](https://user-images.githubusercontent.com/72039923/122451136-17760d00-cfa8-11eb-83ae-6a29b22319ee.png)

I don't know if this is relevant, but I'm using a Raspberry Pi.
Please, resolve, I can't use this script, for now...

**Comment by BiZken** [comment]
I will take a look in to this as soon as possible

**Comment by BiZken** [comment]
> I will take a look in to this as soon as possible

I have now fixed it and it should work if you reclone/download it again
Sorry for the Error, my bad
-BiZken

**Comment by Bellisario** [comment]
Thank you @BiZken, now it works correctly! :wink:
