### ISSUE TITLE
Im stuck pls help

### ISSUE THREAD

**Issue by Mrnoob007** [BiZken/PhishMailer#21]
Hi, bro 
What do i do here. I donno what to type... 🤔
Thank you in advance
Btw do you. Have a wiki how tutorial?
![Screenshot_20210629-150751](https://user-images.githubusercontent.com/86669754/123812209-cf31e580-d8eb-11eb-9e33-5f87e6cacacc.jpg)

**Comment by BiZken** [comment]
I'm working on the wiki as I write this and it should be up soon

**Comment by Mrnoob007** [comment]
Oh

> I'm working on the wiki as I write this and it should be up soon

Oh cool thanks 🙏

**Comment by BiZken** [comment]
A wiki should be up now with the essentials, it will come more soon and I will also create videos on how to use it
