### ISSUE TITLE
Line 9 (In Modulo Requests)

### ISSUE THREAD

**Issue by MagnusDevelopr** [BiZken/PhishMailer#24]
After fixing the error on Line 127 by adding parenthesis at each end. This is the error which shows, I am unable to run this script. 
![Capture](https://user-images.githubusercontent.com/33235220/125313924-58690380-e353-11eb-85d7-e25951be68aa.PNG)

You can check this image for more clarification. 

Also could you please add more clarification if I am doing anything wrong. 

Or any steps on how to do it.

**Comment by BiZken** [comment]
it should work now if you reinstall/clone it again, it was my bad and it should work for you now.
